/*
 * Copyright (C) 2015 Netherlands Forensic Institute
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package nl.minvenj.nfi.smartrank.gui.tabs.crimesceneprofiles;

import static nl.minvenj.nfi.smartrank.raven.ApplicationStatus.VERIFYING_DB;
import static nl.minvenj.nfi.smartrank.raven.ApplicationStatus.WAIT_DB;

import java.util.EnumSet;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import nl.minvenj.nfi.smartrank.gui.tabs.SmartRankPanel;
import nl.minvenj.nfi.smartrank.messages.data.AddCrimeSceneFilesMessage;
import nl.minvenj.nfi.smartrank.messages.status.ApplicationStatusMessage;
import nl.minvenj.nfi.smartrank.raven.ApplicationStatus;
import nl.minvenj.nfi.smartrank.raven.annotations.RavenMessageHandler;

/**
 * This panel contains GUI elements for uploading Crime Scene profiles.
 */
public class CrimeSceneProfilesPanel extends SmartRankPanel {

    private static final Logger LOG = LoggerFactory.getLogger(CrimeSceneProfilesPanel.class);
    private static final EnumSet<ApplicationStatus> DISABLED_STATUS_SET = EnumSet.of(WAIT_DB, VERIFYING_DB);

    public CrimeSceneProfilesPanel() {
        initComponents();
        acceptDroppedFiles(AddCrimeSceneFilesMessage.class);
        registerAsListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _splitPane = new javax.swing.JSplitPane();
        _filePanel = new nl.minvenj.nfi.smartrank.gui.tabs.crimesceneprofiles.CrimeSceneProfilesTopPanel();
        _crimeSceneProfilesBottomPanel = new nl.minvenj.nfi.smartrank.gui.tabs.crimesceneprofiles.CrimeSceneProfilesBottomPanel();

        _splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        _splitPane.setTopComponent(_filePanel);
        _splitPane.setRightComponent(_crimeSceneProfilesBottomPanel);

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(_splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nl.minvenj.nfi.smartrank.gui.tabs.crimesceneprofiles.CrimeSceneProfilesBottomPanel _crimeSceneProfilesBottomPanel;
    private nl.minvenj.nfi.smartrank.gui.tabs.crimesceneprofiles.CrimeSceneProfilesTopPanel _filePanel;
    private javax.swing.JSplitPane _splitPane;
    // End of variables declaration//GEN-END:variables

    @RavenMessageHandler(ApplicationStatusMessage.class)
    public void handleApplicationStatus(final ApplicationStatus status) {
        setEnabled(!DISABLED_STATUS_SET.contains(status));
        LOG.debug("Panel is now {}abled", isEnabled() ? "en" : "dis");
    }
}
